config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :artists, only: %i[show index new create edit update delete]
  resources :reviews, only: %i[index show new create edit update destroy]
  resources :event_artists, only: %i[index show new create edit update delete]
  resources :events do
    resources :venues, only: [:index, :new, :create]
    resources :artists, only: [:index, :new, :create]
  end
  resources :venues, only: %i[index show new create edit update delete]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/artist.rb
require "pg_search"
class Artist < ApplicationRecord
  belongs_to :user
  CATEGORIES = ["Rock", "Indie", "Metal", "Folk", "Jazz", "Blues"]
  has_one_attached :photo
  has_many :event_artists
  has_many :events, through: :event_artists
  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
                  against: %i[name description],
                  # associated_against: { venue: :name, artist: :genre},
                  using: { tsearch: { prefix: true } }
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: %i[show edit update destroy]

  # GET /artists or /artists.json
  def index
    @artists = Artist.all
    if params[:query].present?
      @artists = Artist.search_by_name_and_description(params[:query])
    else
      @artists = Artist.all
    end
  end

  # GET /artists/1 or /artists/1.json
  def show
    @artist = Artist.find(params[:id])
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists or /artists.json
  def create
    @artist = Artist.new(artist_params)
    @artist.user = current_user
    respond_to do |format|
      if @artist.save
        format.html { redirect_to artist_url(@artist), notice: "Artist was successfully created." }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1 or /artists/1.json
  def update
    @artist = Artist.find(params[:id])
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to artist_url(@artist), notice: "Artist was successfully updated." }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1 or /artists/1.json
  def destroy
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url, notice: "Artist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_artist
    @artist = Artist.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def artist_params
    params.require(:artist).permit(:user_id, :name, :genre, :description, :website, :photo)
  end


end

app/views/artists/_form.html.erb
<%= simple_form_for(@artist) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.input :name %>
    <%= f.input :genre %>
    <%= f.input :description %>
    <%= f.input :website %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render "form", artist: @artist %>

<br>

<div>
  <%= link_to "Show this artist", @artist, class:"btn-show" %> |
  <%= link_to "Back to artists", artists_path, class:"btn-back"%>
</div>

app/views/artists/index.html.erb
<div class="events_banner">
  <h2>ARTISTS</h2>
</div>
<div class="artists-searchbar">
  <%= form_with url: artists_path, method: :get, class: "d-flex w-50" do %>
    <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search for artists..." %>
    <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
  <% end %>
</div>
<div class="container">
  <div class="artist-cards-container">
    <% @artists.each do |artist| %>
      <%= link_to artist_path(artist) do %>
        <div class="artist-card">
          <% if artist.photo.attached? %>
            <%= cl_image_tag artist.photo.key %>
          <% else %>
            <img src="https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80" alt="microphone">
          <% end %>
          <div class="artist-card-infos">
            <h3><%= artist.name %></h3>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/artists/new.html.erb
<div class="py-5 container-artist-show">
  <div>
    <%= link_to artists_path, class: "back-arrow" do %>
    <i class="fa-solid fa-circle-arrow-left"></i>
    <% end %>
  </div>
    <div class="row">
     <div class="col-12 col-md-6 offset-lg-3">
      <div class="new-artist-background rounded p-3 shadow">
        <h3 class="text-center">Create your Artist profile </h3>
          <%= simple_form_for @artist do |f| %>
            <%= f.input :name, placeholder: 'Nirvana' %>
            <%= f.input :description, placeholder: 'Tell us about the music' %>
            <%= f.input :website %>
            <%= f.input :genre,
            as: :radio_buttons,
            collection_wrapper_tag: 'div',
            collection_wrapper_class: 'category-wrapper',
            item_wrapper_class: 'category-item',
            input_html: {class: 'category-selector'},
            collection: Artist::CATEGORIES %>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: 'main-button' %>
          <% end %>
      </div>
    </div>
  </div>
</div>


 <%# <%= render "form", artist: @artist %>

app/views/artists/show.html.erb
<div class="container-artist-show">
  <div class="name-banner-artist-show">
    <%= @artist.name %>
  </div>
  <div class="artist-info">
    <div class="artist-info-img">
      <% if @artist.photo.attached? %>
        <%= cl_image_tag @artist.photo.key %>
      <% else %>
        <img src="https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80" alt="microphone">
      <% end %>
    </div>
    <h3>Artist Info</h3>
    <div id="<%= dom_id @artist %>">
      <p>
        <strong>Genre:</strong>
        <%= @artist.genre %>
      </p>
      <p>
        <strong>Description:</strong>
        <%= @artist.description %>
      </p>
      <p>
        <strong>Website:</strong>
        <%= @artist.website %>
      </p>
      <h3>Upcoming Events:</h3>
      <% if @artist.events.first.nil? %>
        <p>No events yet...</p>
      <% else %>
        <div class="event-cards-container">
          <% @artist.events.each do |event|%>
            <%= link_to event_path(event) do %>
              <div class="event-card">
                <% if event.photo.attached? %>
                  <%= cl_image_tag event.photo.key %>
                <% else %>
                  <img src="https://images.unsplash.com/photo-1486556396467-d83d2b23514b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80" alt="smokey scene">
                <% end %>
                <div class="event-card-infos">
                  <h3><%= event.title %></h3>
                  <h5><%= event.venue.name %></h5>
                  <div class="event-card-date-price">
                    <h5><%= event.start_date.strftime("%I:%M %p, %A, %b %d")%></h5>
                    <h4>R <%= event.ticket_price %></h4>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <div class="btns-artist-show">
        <%= link_to "All Artists", artists_path, class:"btn-back" %>
        <%# <%= link_to 'Add to Event', event_artists_path(event_id: session[:event_id], artist_id: @artist.id), method: :post, class:"btn-add"  %>
        <% if current_user == @artist.user %>
          <%= link_to "Edit your profile", edit_artist_path(@artist), class:"btn-edit" %>
          <%= button_to "Delete your profile", @artist, method: :delete, class:"btn-delete"%>
        <% end %>
      </div>
    </div>
  </div>
</div>