config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :artists, only: %i[show index new create edit update delete]
  resources :reviews, only: %i[index show new create edit update destroy]
  resources :event_artists, only: %i[index show new create edit update delete]
  resources :events do
    resources :venues, only: [:index, :new, :create]
    resources :artists, only: [:index, :new, :create]
  end
  resources :venues, only: %i[index show new create edit update delete]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_banner.html.erb
<div class="banner2">
    <img alt="Le Wagon" src="/assets/wide2-d80eef8eca3fbd5d5e1fe3a2207c795370072a2c5f959dcf9e6bcdc6064feddc.JPG" class="banner2">

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Power Ranger Coding
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("logo.png", alt: "Logo") %>
    <% end %>

    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDarkDropdown">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            DISCOVER
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink1">
            <li><%= link_to 'EVENTS', events_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'VENUES', venues_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'ARTISTS', artists_path, class: 'dropdown-item' %></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            CREATE
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink2">
            <li><%= link_to 'EVENT', new_event_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'VENUE', new_venue_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'ARTIST', new_artist_path, class: 'dropdown-item' %></li>
          </ul>
        </li>
      </ul>
    </div>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item nav-link" %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      <% end %>
    </div>
  </div>
</div>