config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :artists, only: %i[show index new create edit update delete]
  resources :reviews, only: %i[index show new create edit update destroy]
  resources :event_artists, only: %i[index show new create edit update delete]
  resources :events do
    resources :venues, only: [:index, :new, :create]
    resources :artists, only: [:index, :new, :create]
  end
  resources :venues, only: %i[index show new create edit update delete]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/venue.rb
class Venue < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user
  has_one_attached :photo
  has_many :events
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: %i[show edit update destroy]

  # GET /venues or /venues.json
  def index
    @venues = Venue.all
    @markers = @venues.geocoded.map do |venue|
      {
        lat: venue.latitude,
        lng: venue.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {venue: venue})
      }
    end
  end

  # GET /venues/1 or /venues/1.json
  def show
    @venue
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
    @venue = Venue.find(params[:id])
  end

  # POST /venues or /venues.json
  def create
    @venue = Venue.new(venue_params)
    @venue.user = current_user
    if @venue.save
      redirect_to @venue, notice: "Venue was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /venues/1 or /venues/1.json
  def update
    @venue = Venue.find(params[:id])
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to venue_url(@venue), notice: "Venue was successfully updated." }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1 or /venues/1.json
  def destroy
    @venue.destroy

    respond_to do |format|
      format.html { redirect_to venues_url, notice: "Venue was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_venue
    @venue = Venue.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def venue_params
    params.require(:venue).permit(:user_id, :name, :description, :latitude, :longitude, :phone_number, :email, :website, :photo, :capacity, :address)
  end
end

app/views/venues/_form.html.erb
<%= simple_form_for(@venue) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name, placeholder: 'JamRock Theatre' %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :website %>
    <%= f.input :email %>
    <%= f.input :capacity %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: 'venue-button' %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/venues/_info_window.html.erb
<div class="marker-info-window">
  <%= link_to venue_path(venue) do %>
    <h4><%= venue.name %></h4>
    <p><%= venue.address %></p>
  <% end %>
</div>

app/views/venues/_venue.html.erb
<div id="<%= dom_id venue %>">

  <p>
    <strong>Name:</strong>
    <%= venue.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= venue.address %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= venue.phone_number %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= venue.email %>
  </p>

  <p>
    <strong>Website:</strong>
    <%= venue.website %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= venue.description %>
  </p>
<h3>Events:</h3>
      <% if venue.events.first.nil? %>
        <p>This venue hasn't hosted any events. Yet...</p>
      <% else %>
        <div class="event-cards-container">
          <% venue.events.each do |event|%>
            <%= link_to event_path(event) do %>
              <div class="event-card">
                <% if event.photo.attached? %>
                  <%= cl_image_tag event.photo.key %>
                <% else %>
                  <img src="https://images.unsplash.com/photo-1486556396467-d83d2b23514b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80" alt="smokey scene">
                <% end %>
                <div class="event-card-infos">
                  <h3><%= event.title %></h3>
                  <h5><%= event.venue.name %></h5>
                  <div class="event-card-date-price">
                    <h5><%= event.start_date.strftime("%I:%M %p, %A, %b %d")%></h5>
                    <h4>R <%= event.ticket_price %></h4>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
</div>

app/views/venues/edit.html.erb
<div class="container">
  <h1>Editing venue</h1>

  <%= render "form", venue: @venue %>

  <br>

  <div>
    <%= link_to "Show this venue", @venue %> |
    <%= link_to "Back to venues", venues_path %>
  </div>
</div>

app/views/venues/index.html.erb
<%# <p style="color: green"><%= notice</p> %>
<div class="events_banner">
  <h2>VENUES</h2>
</div>

<div class="venues-container">
  <div class="venue-cards-container">
    <% @venues.each do |venue| %>
      <%= link_to venue_path(venue) do %>
        <div class="venue-card">
          <div class="venue-card-image">
            <%= cl_image_tag venue.photo.key %>
          </div>
          <div class="venue-card-infos">
            <h3> <%= venue.name %> </h3>
            <p><%= truncate(venue.description, length: 210, separator: /\s/) %></p>
            <div class="venue-card-infos-bottom">
              <div class="venue-icon-and-info">
                <h6><i class="fa-solid fa-phone"></i></h6>
                <h6><%= venue.phone_number %></h6>
              </div>
              <div class="venue-icon-and-info">
                <h6><i class="fa-solid fa-users"></i></h6>
                <h6><%= venue.capacity %></h6>
              </div>
              <div class="venue-icon-and-info">
                <h6><i class="fa-solid fa-envelope"></i></h6>
                <h6><%= venue.email %></h6>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="venues-map"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/venues/new.html.erb
<div class="py-5 container-venue-show">
  <div>
    <%= link_to venues_path, class: "back-arrow" do %>
      <i class="fa-solid fa-circle-arrow-left"></i>
    <% end %>
  </div>
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="new-artist-background rounded p-3 shadow">
        <h3 class="text-center">Add your venue details</h3>
          <%= simple_form_for @venue do |f| %>
            <%= f.input :name, placeholder: 'JamRock Theatre' %>

            <%= f.input :address %>
            <%= f.input :phone_number %>
            <%= f.input :website %>
            <%= f.input :email %>
            <%= f.input :capacity %>
            <%= f.input :description %>
            <%= f.input :photo, as: :file %>
            <%= f.submit class: 'venue-button' %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/venues/show.html.erb
<div class="container-venue-show">
  <div class="venue-info">
    <div class="venue-show-top-info">
      <div class="venue-show-image-section">
        <%= cl_image_tag @venue.photo.key %>
      </div>
      <div class="venue-show-infos-section">
        <div class="venue-show-name-description">
          <h2><%= @venue.name %></h2>
          <div class="venue-show-description">
            <p><%= @venue.description %></p>
          </div>
          <div class="venue-show-infos-bottom">
            <div class="venue-icon-and-info">
              <h6><i class="fa-solid fa-phone"></i></h6>
              <h6><%= @venue.phone_number %></h6>
            </div>
            <div class="venue-icon-and-info">
              <h6><i class="fa-solid fa-users"></i></h6>
              <h6><%= @venue.capacity %></h6>
            </div>
            <div class="venue-icon-and-info">
              <h6><i class="fa-solid fa-envelope"></i></h6>
              <h6><%= @venue.email %></h6>
            </div>
          </div>
          <h4>Upcoming Events:</h4>
          <div class="venue-show-events-section">
            <% if @venue.events != [] %>
              <% @venue.events.each do |event| %>
                <%= link_to event_path(event) do %>
                  <div class="venue-show-event-card">
                    <% if event.photo.attached? %>
                      <%= cl_image_tag event.photo.key %>
                    <% else %>
                      <img src="https://images.unsplash.com/photo-1486556396467-d83d2b23514b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80" alt="smokey scene">
                    <% end %>
                    <div class="venue-show-event-card-infos">
                      <h3><%= event.title %></h3>
                      <div class="venue-show-event-card-date-price">
                        <h5><%= event.start_date.strftime("%A, %b %d")%></h5>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% else %>
              <p>No events yet...</p>
            <% end %>
          </div>
          <div class="btns-venue-show">
            <%= link_to "Back to venues", venues_path, class:"venue-button"  %>
            <%= link_to "Edit venue", edit_venue_path(@venue), class:"venue-button" %>
            <%= button_to "Delete venue", @venue, method: :delete, class:"venue-button"  %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>